version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ${PWD}:/etc
    command: ["--config", "/etc/otel-config.yaml"]
    ports:
      - "55680:55680"  # OTLP gRPC receiver
      - "55681:55681"  # OTLP HTTP receiver
      - "4318:4318"    # OTLP HTTP receiver (alternative port)
      - "4317:4317"    # OTLP gRPC receiver (alternative port)
